/**
 * Stamps a build identity both halves of AutoWebMCP can compare.
 *
 * The Studio page and the Teach Mode extension are built and reloaded
 * separately, by hand, in a browser. Reloading one and not the other is
 * silent and produces confident, wrong results — an evening was spent
 * diagnosing behaviour that had already been fixed but was not loaded.
 * A stamp makes that visible instead of memorable.
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const stamp = new Date().toISOString();
await writeFile(
  join(process.cwd(), "src", "buildStamp.ts"),
  `/** Generated by scripts/stamp.mjs. Compared between the page and the extension. */\n` +
    `export const BUILD_STAMP = ${JSON.stringify(stamp)};\n`
);
console.log(`build stamp ${stamp}`);
